### ISSUE TITLE
validate_target! throws errors for URL encoded query strings

### ISSUE THREAD

**Issue by lucaspiller** [ericmj/mint#110]
Query strings (and paths?) can contain URL encoded characters, for example `http://localhost:3000?data=%7B%22hello%22%3A%22world%22%7D`.

When making a request to an URL like this with Mint, it returns an error as `validate_target!` deems the URL invalid:

```elixir
iex(1)> {:ok, conn} = Mint.HTTP.connect(:http, "localhost", 3000)                                                                                                                                                                            
iex(2)> {:ok, conn, request_ref} = Mint.HTTP.request(conn, "GET", "/?data=%7B%22hello%22%3A%22world%22%7D", [], "")
** (MatchError) no match of right hand side value: {:error, %Mint.HTTP1{buffer: "", host: "localhost", private: %{}, request: nil, requests: {[], []}, socket: #Port<0.1027>, state: :open, transport: Mint.Core.Transport.TCP}, :invalid_request_target}
```
The test for this gives the example of a path `/ /`, however curl happily makes a request for this, so is this validation even needed?

```
$ curl -v "http://localhost:3000/ /"                                                                                                                                                                     
> GET / / HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
```

**Comment by ericmj** [comment]
The validation is needed because without it you can send requests that break the protocol.

We should check for both already escaped characters `%NN` and characters that are allowed to be unescaped. Today we only do the latter.
