### ISSUE TITLE
Add open_request_count/1

### ISSUE THREAD

**Issue by whatyouhide** [ericmj/mint#115]
We could add a function that returns the number of open (in-flight) requests. In HTTP/1 this tells the number of pipelined requests. In HTTP/2 this tells the number of open streams and is useful for either checking how many streams you can open and also for testing that we close streams correctly without using the internal structure of the connection in tests.

**Comment by whatyouhide** [comment]
@ericmj how can we do this in HTTP/2, where we have both client-initiated streams and server-initiated streams? The spec says that only client-initiated streams count towards the server max concurrent streams limit, so I think users would mostly be interested in that. But maybe we should make the count of server-initiated streams accessible too?

**Comment by ericmj** [comment]
Yeah, should make both available or document that it is only for client initiated requests.

**Comment by whatyouhide** [comment]
@ericmj any preference? I think I would go with client-initiated only for now, given that's the semantics of HTTP/1 and given that clients probably won't care about how many server-initiated requests there are since it doesn't affect how many the clients can open.

**Comment by ericmj** [comment]
Sounds good.
