### ISSUE TITLE
Decide whether we should return always :error or sometimes :ok in stream/2 for gracefully closed connection

### ISSUE THREAD

**Issue by whatyouhide** [ericmj/mint#152]
Scenarios to consider:
* GOAWAY frame with NO_ERROR
* connection: close header
* tcp_closed message without any open requests or streams

**Comment by AnilRedshift** [comment]
IMO these are all valid HTTP states, and thus :ok should be returned. It would be better to have client implementations handle this, rather than making decisions at this layer.

**Comment by whatyouhide** [comment]
@AnilRedshift they indeed are valid states, but they change the state of the connection in a way that will affect user operations. If the connection gets closed, then the user won't be able to send requests on it anymore. That's why I'm not convinced returning `:ok` as if nothing happened is the way to go. However, I don't have any better ideas yet 😄

**Comment by AnilRedshift** [comment]
Maybe a third way would be to emit control codes into the stream? `{:control, :go_away}`

**Comment by ericmj** [comment]
@AnilRedshift That breaks what a response is, a response is about a request/stream but GOAWAY is for the whole connection.
