### ISSUE TITLE
Passive mode support

### ISSUE THREAD

**Issue by scohen** [ericmj/mint#170]
There should be a way to support blocking request / responses. The problem I had stemmed from trying to integrate mint as the transport to a db_connection connection process. The active mode `{:tcp, ...` messages were swallowed by db_connection.

**Comment by whatyouhide** [comment]
The support for this would require increasing the API surface since we'd have to have `Mint.recv/3` given that we don't expose the socket anywhere.

**Comment by ericmj** [comment]
I think it's better to expose the socket and let the user handle the receiving like they today in active mode.

**Comment by whatyouhide** [comment]
@ericmj actually, you're probably right. Doing that will also enable users to map socket to connection so that when they receive a TCP/SSL message they don't have to do the `Mint.stream/2` dance on all the connections to find the one that doesn't return `:unknown`. However, how do we handle things like recv returning errors directly to the user? Also, how do we stream data back to Mint without the TCP/SSL message (as in, what API do we use)?

**Comment by ericmj** [comment]
We can document for the user how to use passive mode and how to wrap the return values from recv/2 in active mode messages.

**Comment by ericmj** [comment]
I think this is the best choice for now because in Mint we would only need an option to disable the calls to set `active: :once`.

**Comment by whatyouhide** [comment]
I guess that API is fine even if I don't really like users having to know about `{:tcp, socket, data}` messages. But still I'm wondering how would we fix `:gen_tcp.recv/3` returning `{:error, reason}` to the user directly. 🤔

**Comment by scohen** [comment]
Thank you @whatyouhide  and @ericmj

**Comment by whatyouhide** [comment]
@scohen no problem. Incoming is also `Mint.HTTP.controlling_process/2` which you might want if you're playing with DBConnection :)

**Comment by fishcakez** [comment]
DBConnection adapters should never call controlling process. The
abstraction is built on the principle that active mode and controlling
process are too hard to use to write correctly.

**Comment by scohen** [comment]
Thanks, @fishcakez; I was scratching my head a bit about where I'd need it.
