### ISSUE TITLE
Sometime result response's parts do not include {:status, #Reference<...>, response_code}

### ISSUE THREAD

**Issue by blisscs** [ericmj/mint#175]
Hi, 

I am having an issue that sometimes Mint doesn't include `{:status, #Reference<...>, response_code}` in the response.

Given the code below -

```elixir
  ## Some code has been removed for simplicity
  alias Mint.HTTP
  

  def handle_info(msg, {conn, request_ref}) do
    case HTTP.stream(conn, msg) do
      :unknown ->
        {:noreply, {conn, request_ref}}

      {:ok, conn, response} ->
        if {:done, request_ref} in response do
          {:data, ^request_ref, result} = List.keyfind(response, :data, 0)
          # Debugging          
          IO.inspect List.keyfind(response, :status, 0)
          # sometimes I get nil
          # sometimes I get {:status,#Reference<...>, 200} 

          {:status, ^request_ref, code} = List.keyfind(response, :status, 0)
          handle_result(code, result)
        end
        {:noreply, {conn, request_ref}}
    end
  end
```

From the above code, I am using `handle_info/2` to handle receive messages. I am using `Mint.HTTP.stream/2` to fetch out mint's related values and then handle them per case.

If you see from the code I am waiting until `{:done, request_ref}` is in the response body by testing `{:done, request_ref} in response` before I continuing to do something with the response.

The issue is that, sometimes this `List.keyfind(response, :status, 0)` returns `nil`. In this case, I am not so sure why the status code's tuple is not there in the result response, which should not be happened. As far as I know, all http responses should have accompanied the status code.

--
Dev

**Comment by ericmj** [comment]
The :status, :headers, :data, and :done responses can be split over multiple messages. You need to accumulate the responses until you receive :done.

**Comment by blisscs** [comment]
Thank you for the update. Now I understand thing more clearly.

I got another question will there be possibility that same type of response be spread on more than one message?

For ex.
[{:data, ref, data1}] in message1
and [{:data, ref, data2}]

If this is possible, to get the complete data I will have to contact data1 and data2 to get the the real data. Am I right?

**Comment by ericmj** [comment]
Yes, :data and :headers can be split over multiple messages. Mint is streaming so the response is streamed in parts.

**Comment by blisscs** [comment]
Thank you @ericmj.

I am closing issue now.
