### ISSUE TITLE
Add a page in the docs about dealing with decompression

### ISSUE THREAD

**Issue by dbernheisel** [ericmj/mint#183]
Any plans to support decompression of gzipped, zipped, or deflated bodies?  

I'm not sure how this would actually work with streams, since decompressing using erlang's [zlib](http://erlang.org/doc/man/zlib.html) mostly needs the complete content before decompressing.

- [Tesla supports decompression](https://github.com/teamon/tesla/blob/v1.2.1/lib/tesla/middleware/compression.ex)
- Hackney and HTTPoison do not.
- ibrowse and HTTPotion do not (as far I see)

I've been bitten by this before and handled it myself after the request, and don't want others to be surprised. If you're interested to support this, I'll be happy to research more and contribute; if not code then maybe a small guide on how the user can handle it.

**Comment by whatyouhide** [comment]
@dbernheisel let's start with documentation on how to do this. We would absolutely love it if you contributed that, but let us know if you prefer we do it. After that, we can talk about support in Mint or through adapters.

**Comment by whatyouhide** [comment]
I've renamed this to highlight that this is only for documentation.

**Comment by dbernheisel** [comment]
Thanks. I'll be happy to write up an example repo, write a guide, and PR it here.

**Comment by whatyouhide** [comment]
@dbernheisel I'd skip the example repo and just go for a page in the docs (`/pages` in this repo) :)

**Comment by whatyouhide** [comment]
Closing in favour of the PR #191. 🎉
