### ISSUE TITLE
Add a guide on how to deal with redirects

### ISSUE THREAD

**Issue by whatyouhide** [ericmj/mint#190]
Maybe we need one (after getting #185). @ericmj wdyt?

**Comment by ericmj** [comment]
Yeah, could be a good to have a section with some common problems and their solutions.

**Comment by zbarnes757** [comment]
I can try to add some documentation for it if no one else has already claimed this.

**Comment by whatyouhide** [comment]
@zbarnes757 that would be appreciated, thank you!

**Comment by whatyouhide** [comment]
Closing in favor of the PR (#206).
