### ISSUE TITLE
server not responding, gen_server hanging

### ISSUE THREAD

**Issue by ggerico** [ericmj/mint#199]
I am using the architecture mentioned in the documentation *Wrapping a Mint connection in a GenServer*. 

I've got troubles when the server I am sending a post request to (push_message of the [Line API](https://developers.line.biz/en/docs/)), does receive the messages on their server but doesn't return a 200 status response to the GenServer which is waiting for ...  

> As the GenServer will only reply to the caller once a response comes from the server
the caller is just blocked.

the last line on the console is:
the request_ref is: #Reference<0.1535639387.2296643585.210860>

Should I try to use a timeout?

**Comment by ericmj** [comment]
The example code in "Wrapping a Mint connection in a GenServer" uses the default timeout of 5 seconds. Have you changed this?

**Comment by ggerico** [comment]
02:13:22.718 request_id=FbdBTumw2AJTl7cAAAFx [info] POST /api/line_channel
02:13:22.720 request_id=FbdBTumw2AJTl7cAAAFx [debug] Processing with PizzaDeliveryWeb.LineChannelController.create/2
  Parameters: %{"destination" => "U021a0496889574df01e2622beaced5d5", "events" => [%{"message" => %{"id" => "10324527522198", "text" => "again", "type" => "text"}, "replyToken" => "86082465c2b04cc6938a169d9c503716", "source" => %{"type" => "user", "userId" => "*************"}, "timestamp" => 1564791202036, "type" => "message"}]}
  Pipelines: [:api]
Line Signature Genuine
02:13:22.844 [info] the request_ref is: #Reference<0.1817255119.1902903297.36193>
02:13:23.160 [info] the website responded: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.31>, :tls_connection, :undefined}, [#PID<0.2853.0>, #PID<0.2852.0>]}, "HTTP/1.1 200 OK\r\nServer: nginx\r\nContent-Type: application/json;charset=UTF-8\r\nx-line-request-id: b177b114-c560-41db-b187-6496e862bd18\r\nx-content-type-options: nosniff\r\nx-xss-protection: 1; mode=block\r\nx-frame-options: DENY\r\nContent-Length: 204\r\nX-EdgeConnect-MidMile-RTT: 223\r\nX-EdgeConnect-Origin-MEX-Latency: 27\r\nExpires: Sat, 03 Aug 2019 00:13:23 GMT\r\nCache-Control: max-age=0, no-cache, no-store\r\nPragma: no-cache\r\nDate: Sat, 03 Aug 2019 00:13:23 GMT\r\nConnection: keep-alive\r\n\r\n{\"userId\":\"U2f255c4187294372f91260cd8935a214\",\"displayName\":\"Germain 項捷曼\",\"pictureUrl\":\"https://profile.line-scdn.net/0hwzlCVBuAKFVROgLqkdZXAm1_JjgmFC4dKVpkMHZudzd5WDsFOAlnZ3Nuf2IoXT8KaFtvYHNqJmd7\"}"}
02:13:23.162 [info] Received responses: [{:status, #Reference<0.1817255119.1902903297.36193>, 200}, {:headers, #Reference<0.1817255119.1902903297.36193>, [{"server", "nginx"}, {"content-type", "application/json;charset=UTF-8"}, {"x-line-request-id", "b177b114-c560-41db-b187-6496e862bd18"}, {"x-content-type-options", "nosniff"}, {"x-xss-protection", "1; mode=block"}, {"x-frame-options", "DENY"}, {"content-length", "204"}, {"x-edgeconnect-midmile-rtt", "223"}, {"x-edgeconnect-origin-mex-latency", "27"}, {"expires", "Sat, 03 Aug 2019 00:13:23 GMT"}, {"cache-control", "max-age=0, no-cache, no-store"}, {"pragma", "no-cache"}, {"date", "Sat, 03 Aug 2019 00:13:23 GMT"}, {"connection", "keep-alive"}]}, {:data, #Reference<0.1817255119.1902903297.36193>, "{\"userId\":\"U2f255c4187294372f91260cd8935a214\",\"displayName\":\"Germain 項捷曼\",\"pictureUrl\":\"https://profile.line-scdn.net/0hwzlCVBuAKFVROgLqkdZXAm1_JjgmFC4dKVpkMHZudzd5WDsFOAlnZ3Nuf2IoXT8KaFtvYHNqJmd7\"}"}, {:done, #Reference<0.1817255119.1902903297.36193>}]

**Comment by ericmj** [comment]
In the first log you are sending one request but the server is responding twice. Have you removed things from the log?

Unfortunately it's not possible for us to look into this without code that reproduces the issues. Otherwise we are just looking at logs from code we don't know.

**Comment by ggerico** [comment]
`the website responded` is logged when handle_info is called.
`Received responses` is logged when the `Mint.Http.stream` returns `{:ok, conn, responses}`.
As you supposed, it seems that `stream/2` is blocking.

Below the module: 

```elixir
defmodule MyApp.HttpClient do

  use GenServer

  require Logger

  defstruct [:conn, requests: %{}] # %PizzaDeliveryWeb.HttpClient{conn: nil, requests: %{}}

  # Interface

  def start_link({scheme, host, port}) do
    GenServer.start_link(__MODULE__, {scheme, host, port}) #owner + message
  end

  def request(pid, method, path, headers, body) do
    GenServer.call(pid, {:request, method, path, headers, body})
  end

  def close_connection(pid) do
    GenServer.cast(pid, :close_connection)
  end

  def connection_open?(pid) do
    GenServer.call(pid, :connection_open)
  end

  def stop(pid, reason \\ :normal, timeout \\ :infinity) do
    GenServer.stop(pid, reason, timeout)
  end

  ## Callbacks

  @impl true
  def init({scheme, host, port}) do
    with {:ok, conn} <- Mint.HTTP.connect(scheme, host, port) do
      state = %__MODULE__{conn: conn}
      {:ok, state}
    end
  end

  @impl true
  def handle_call({:request, method, path, headers, body}, from, state) do
    case Mint.HTTP.request(state.conn, method, path, headers, body) do
      {:ok, conn, request_ref} ->
        Logger.info(fn -> "the request_ref is: #{inspect(request_ref)}" end)
        state = put_in(state.conn, conn)
        state = put_in(state.requests[request_ref], %{from: from, response: %{}})
              {:noreply, state,}

      {:error, conn, reason} ->
        state = put_in(state.conn, conn)
        Logger.error(fn -> "the request got an error: #{inspect(reason)}" end)
        {:reply, {:error, reason}, state}
    end
  end

  def handle_call(:connection_open, _from, state) do
    {:reply, Mint.HTTP.open?(state.conn), state}
  end

   @impl true
  def handle_cast(:close_connection, state) do
    {:ok, conn} = Mint.HTTP.close(state.conn)
    {:noreply, put_in(state.conn, conn)}
  end

  @impl true
  def handle_info(message, state) do
      Logger.info("the website responded: #{inspect(message)}")
    case Mint.HTTP.stream(state.conn, message) do
      :unknown ->
        _ = Logger.error(fn -> "Received unknown message: " <> inspect(message) end)
        {:noreply, state}

      {:ok, conn, responses} ->
        _ = Logger.info(fn -> "Received responses: " <> inspect(responses) end)
        state = put_in(state.conn, conn)
        state = Enum.reduce(responses, state, &process_response/2)
        {:noreply, state}

      {:error, conn, error, _responses} ->
        state = put_in(state.conn, conn)
        _ = Logger.error(fn -> "Received error message: " <> inspect(error) end)
        {:noreply, state}
    end
  end

  @impl true
  def terminate(reason, state) do
    Logger.info(fn -> "the httpclient is done with reason #{inspect(reason)}, requests done: #{inspect(state)}" end)
  end

  defp process_response({:status, request_ref, status}, state) do
    put_in(state.requests[request_ref].response[:status], status)
  end

  defp process_response({:headers, request_ref, headers}, state) do
    put_in(state.requests[request_ref].response[:headers], headers)
  end

  defp process_response({:data, request_ref, new_data}, state) do
    update_in(state.requests[request_ref].response[:data], fn data -> (data || "") <> new_data end)
  end

  defp process_response({:done, request_ref}, state) do
    Logger.info("It's done! state: #{inspect(state)}")
    {%{response: response, from: from}, state} = pop_in(state.requests[request_ref])
    GenServer.reply(from, {:ok, response})
    state
  end

end
```

**Comment by ericmj** [comment]
Unless you can give us a reliable way to reproduce this we can only try to reproduce ourselves.

For us to reproduce we need to have the same state of the connection as you have. To get to this state we need the full log of requests you make and TCP messages returned from the server since you opened the connection.

Right now there is too much missing from the logs, for example, as I mentioned before you get two two HTTP responses but we can only see you making one request in the logs which is not possible.

> Sometimes also request/5 returns {:ok, conn, request_ref} and the handle_info/2 is never called.

This is something you have to handle in your code. It's definitely a possibility that the server will not respond to a request.

**Comment by ggerico** [comment]
The trouble is I can't reproduce the behavior of the server yet, it is really messy. Thanks for your replies.
