### ISSUE TITLE
Handle PRIORITY frames

### ISSUE THREAD

**Issue by whatyouhide** [ericmj/mint#207]
Right now we just log them and ignore them.

**Comment by whatyouhide** [comment]
@ericmj let's quickly discuss API.

Priority information is formed by three components:

  * `exclusive?` - a boolean that tells if the stream dependency is exclusive
  * `stream_dependency` - a stream ID that the stream where the PRIORITY is sent on depends on
  * `weight` - a relative weight in `1..256` (compared to the parent)

## Incoming priority information

The priority can be set from the server in two ways: either in the HEADERS frame (optionally) or as PRIORITY frames.

I think we can introduce a new response:

  * `{:priority, ref, {exclusive?, req_dependency_ref, weight}}` - We'll always either have no priority info or all three, so I think a tuple makes sense.

This response will be returned after `{:headers, ...}` if the priority info is in the HEADERS frame, or whenever a PRIORITY frame is received.

A challenge here is to translate the `stream_dependency` (which is a stream ID) to a reference. What happens if we don't have that stream_id saved in the connection state anymore?

## Outgoing priority information

We need to support outgoing priority information. I propose the same priority format with the 3-element tuple or `nil`. Since the root of the "dependency tree" is always the stream `0`, I propose that `stream_dependency` can be either a ref or `nil` (to indicate stream `0`).

We'll need to support:

  * a `:priority` option in `request/6`
  * a `:priority` option in `stream_request_body/4` (doesn't support options yet, we should add that)
  * a `set_priority(conn, request_ref, priority_info_tuple)` function to send PRIORITY frames

This is slightly complex. I don't know if it's worth it. Thoughts? PRIORITY is a *suggestion* so we might get away with not implementing it until someone comes in and asks for this feature, especially since it doesn't cause any breaking changes.

**Comment by ericmj** [comment]
> A challenge here is to translate the stream_dependency (which is a stream ID) to a reference. What happens if we don't have that stream_id saved in the connection state anymore?

Maybe it would be better to expose the stream_id to users and let them track this?

> Since the root of the "dependency tree" is always the stream 0, I propose that stream_dependency can be either a ref or nil (to indicate stream 0).

With `set_priority/4` his has the same problem, right? You need to make sure to set the priority before Mint sends the `:done` response and drops the reference?

> This is slightly complex. I don't know if it's worth it. Thoughts? PRIORITY is a suggestion so we might get away with not implementing it until someone comes in and asks for this feature, especially since it doesn't cause any breaking changes.

Regardless, it would be nice to have an idea of the API so we don't make breaking changes. The change to `request/6` is a good step in that direction.

**Comment by whatyouhide** [comment]
> Maybe it would be better to expose the stream_id to users and let them track this?

If we expose the stream_id, then we have a case where a process holds more than one HTTP/2 connections but keeps a single map of responses that are streaming. Currently, that's possible thanks to the ref, but if we introduce stream_ids, it might not be possible. We could make the request reference `{stream_id, conn.socket}` though, and that might work. Thoughts?

**Comment by whatyouhide** [comment]
@ericmj I vote that we close this for now and leave it for the future. Nothing in the API should break when we go and introduce this. Wdyt?

**Comment by ericmj** [comment]
Sounds good, #209 has the preparations in the API for this.
