### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by l-vincent-l** [ericmj/mint#214]
I have a problem running this code :
```elixir
uri = URI.parse("https://www.sudmobilite.fr/")
Mint.HTTP.connect(String.to_atom(uri.scheme), uri.host, uri.port)
```
I have this error:
`{:error, %Mint.TransportError{reason: :closed}}`

The reason isn't really meaningful.
This works perfectly with curl.
Here he's the trace:
```
* Expire in 2 ms for 1 (transfer 0x55e78be0a5c0)
*   Trying 195.200.184.140...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55e78be0a5c0)
* Connected to www.sudmobilite.fr (195.200.184.140) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=www.sudmobilite.fr
*  start date: Aug  4 06:00:15 2019 GMT
*  expire date: Nov  2 06:00:15 2019 GMT
*  subjectAltName: host "www.sudmobilite.fr" matched cert's "www.sudmobilite.fr"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> GET /WebServices/ExportService/Gtfs.aspx?key=PACA&operatorCode=CG13 HTTP/1.1
> Host: www.sudmobilite.fr
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: private
< Content-Length: 689267
< Content-Type: application/octet-stream
< Last-Modified: Wed, 04 Sep 2019 07:00:34 GMT
< Server: Microsoft-IIS/7.5
< Set-Cookie: ASP.NET_SessionId=3clkvk3fuuxcptzvmtaqxy1d; path=/; HttpOnly
< Content-Disposition: attachment; filename=CG13.GTFS.zip
< X-AspNet-Version: 4.0.30319
< X-Powered-By: ASP.NET
< Date: Thu, 19 Sep 2019 15:38:39 GMT
```
Am I missing something?

**Comment by whatyouhide** [comment]
I can reproduce this. We're failing to connect through `:ssl.connect/3` basically, so my guess is something to do with the SSL options, which in turn makes me thing of something cipher-related or something. I'll play my usual @voltone card because I suck at SSL and he is very kind and hasn't blocked me on GitHub yet 😄

**Comment by voltone** [comment]
After that big ❤️ on stage in Denver how could I refuse, @whatyouhide 

The server has an odd set of cipher suites enabled. It enables some ECDHE suites and some AES-GCM suites, but it does not support the combination of the two. So curl connects using ECDHE with AES-CBC mode.

In Mint, CBC suites are disabled by default, in accordance with the HTTP/2 RFC. And falling back to RSA key exchange is not an option, for the same reason.

As mentioned in the [Mint docs](https://hexdocs.pm/mint/Mint.HTTP.html#connect/4-supporting-older-cipher-suites), the workaround is to enable the OTP default cipher suites:

```elixir
Mint.HTTP.connect(
  String.to_atom(uri.scheme),
  uri.host,
  uri.port,
  transport_opts: [ciphers: :ssl.cipher_suites(:default, :"tlsv1.2")]
)
```

**Comment by l-vincent-l** [comment]
Thank you for your quick replies.
What is the best strategy here? Always use the options provided in @voltone comment or, do multiple calls, with different and stop when it works?

**Comment by voltone** [comment]
From a security perspective there is not much point to try first with only the strong ciphers and then retry with the weaker ones. Normally the server would pick the strongest mutually supported option, and if the server doesn't have a preference then it depends on the client list (`:ssl.cipher_suites(:default, :"tlsv1.2")` is pretty much sorted from strong to weak). So even without retrying, properly configured servers will end up negotiating a strong cipher suite.

So in applications where you know you are going to have to work with servers that are not compatible with the HTTP/2 RFC cipher suites, or if you just don't know what you're going to encounter, use `:ssl.cipher_suites(:default, :"tlsv1.2")`.

**Comment by l-vincent-l** [comment]
Ok.
If there's no problem of security, why it isn't the default options?

**Comment by voltone** [comment]
I meant there is no difference between trying with the weak ciphers right away versus trying with strong ciphers first and then trying again with the weak ones. Using *only* the strong defaults is preferred, but in this particular case that would require the server config to be fixed (perhaps worth a try, if you can reach out to them)

**Comment by whatyouhide** [comment]
I think we can close this issue since as @voltone pointed out, we want Mint to be as secure as possible out of the box. Thanks @l-vincent-l, and thanks @voltone for your usual super useful help! 💟

**Comment by ijunaid8989** [comment]
@whatyouhide sorry to bother you here. but I am having this issue all of a sudden

```elixir
iex(api_server@88.99.215.251)1> Evercam.HTTP.get("https://rest.nexmo.com/sms/json")
{:error,
 %Mint.TransportError{
   reason: {:tls_alert,
    {:handshake_failure,
     'TLS client: In state certify at ssl_handshake.erl:1840 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,invalid_key_usage}'}}
 }}
```

it was working an hour ago. I am using Finch btw..

can you give any heads up? or any direction should I look?

**Comment by ericmj** [comment]
@ijunaid8989 It is working for me:

```
{:ok, #PID<0.632.0>}
iex(2)> Finch.build(:get, "https://rest.nexmo.com/sms/json") |> Finch.request(Foo)
{:ok,
 %Finch.Response{
   body: "{\n    \"message-count\": \"1\",\n    \"messages\": [{\n        \"status\": \"2\",\n        \"error-text\": \"Missing api_key\"\n    }]\n}",
   headers: [
     {"date", "Wed, 15 Dec 2021 15:57:34 GMT"},
     {"content-type", "application/json"},
     {"transfer-encoding", "chunked"},
     {"connection", "keep-alive"},
     {"server", "envoy"},
     {"cache-control", "max-age=1"},
     {"content-disposition", "attachment; filename=\"api.txt\""},
     {"x-nexmo-trace-id", "6604006eafb00aa24baf0a6bfa6dac1b"},
     {"x-envoy-upstream-service-time", "95"},
     {"x-frame-options", "deny"},
     {"x-xss-protection", "1; mode=block"},
     {"strict-transport-security", "max-age=31536000; includeSubdomains"},
     {"x-content-type-options", "nosniff"}
   ],
   status: 200
 }}
```

**Comment by ijunaid8989** [comment]
> @ijunaid8989 It is working for me:
> 
> ```
> iex(1)> Finch.start_link(name: Foo)
> {:ok, #PID<0.632.0>}
> iex(2)> Finch.build(:get, "https://rest.nexmo.com/sms/json") |> Finch.request(Foo)
> {:ok,
>  %Finch.Response{
>    body: "{\n    \"message-count\": \"1\",\n    \"messages\": [{\n        \"status\": \"2\",\n        \"error-text\": \"Missing api_key\"\n    }]\n}",
>    headers: [
>      {"date", "Wed, 15 Dec 2021 15:57:34 GMT"},
>      {"content-type", "application/json"},
>      {"transfer-encoding", "chunked"},
>      {"connection", "keep-alive"},
>      {"server", "envoy"},
>      {"cache-control", "max-age=1"},
>      {"content-disposition", "attachment; filename=\"api.txt\""},
>      {"x-nexmo-trace-id", "6604006eafb00aa24baf0a6bfa6dac1b"},
>      {"x-envoy-upstream-service-time", "95"},
>      {"x-frame-options", "deny"},
>      {"x-xss-protection", "1; mode=block"},
>      {"strict-transport-security", "max-age=31536000; includeSubdomains"},
>      {"x-content-type-options", "nosniff"}
>    ],
>    status: 200
>  }}
> ```

hmm, we havent changed anything in API level, not in code not on system level.

Elixir: 1.12.2
erlang: 23.0

:finch, "0.6.0"

we are on the same versions for almost 6 months or more.

**Comment by ericmj** [comment]
Is it possible the server is having intermittent issues? There seems to be an AWS outage right now which may affect things.

**Comment by ijunaid8989** [comment]
@ericmj actually, it works for me as well on system level when I just use curl
```
root@Ubuntu-1704-zesty-64-minimal:~# curl https://rest.nexmo.com/sms/json
{
    "message-count": "1",
    "messages": [{
        "status": "2",
        "error-text": "Missing api_key"
    }]
```
So I am not sure either now. 

we did an update on `Bump phoenix from 1.6.2 to 1.6.4 ` but I dont think its relevant.

**Comment by ericmj** [comment]
Did any other dependencies also update? Check the diff on `mix.lock`.

**Comment by doublej74** [comment]
I experience exactly the same problem. Suddenly my servers are not able to get to the nexmo sms api anymore.
@ijunaid8989, did you find the cause and/or workaround?
