### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by collegeimprovements** [ericmj/mint#92]
Does `mint` respect `http_proxy` and other environment variables. Since many of us are behind corporate firewall, this is inevitable for us.

**Comment by ericmj** [comment]
We support proxying, see the docs [1] on how to use it. The environment variables are not supported, they would have to be read by the user of the library.

[1] https://hexdocs.pm/mint/Mint.HTTP.html#connect/4-proxying

**Comment by whatyouhide** [comment]
I think this can be closed since as Eric mentioned this is supported, it's just that the user has to manually read the variables.

**Comment by collegeimprovements** [comment]
Does it support username and password in proxy ?
Where should we put username and password of the proxy in `{scheme, hostname, port, opts}`  ?

**Comment by ericmj** [comment]
No, but you can set headers for the proxy in the `:proxy_headers` option.
