### ISSUE TITLE
Find a way to correctly garbage collect HTTP/2 streams

### ISSUE THREAD

**Issue by whatyouhide** [ericmj/mint#99]
Right now we never clean up HTTP/2 streams. The reason is that a stream in the :closed state is still effectively useful because data might still come on that stream. We ignore that data but still. The problem might be that we keep a request ref to stream ID mapping, because if we didn't have that we could just remove a stream and have like a set of closed stream IDs that we can avoid garbage collecting. But with the request ref to stream ID mapping, we would also need to keep the mapping in place for every closed stream and it might leak too much memory. We need to find a way to fix this.

**Comment by ericmj** [comment]
Right now I think we discard all data received on a closed stream, correct? What would we lose by removing all references to closed streams and ignoring frames from stream IDs we do not track?
